version: '3.2'
# Network
networks:
  ithings_net:
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  ithings:
    image: ghcr.io/i4de/ithings:latest
    container_name: ithings
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - ../../deploy/conf/ithings/apisvr/etc:/ithings/etc
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        ipv4_address: 172.19.0.8

  nats-server:
    image: nats:2.8-alpine
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        ipv4_address: 172.19.0.2

  etcd:
    image: docker.io/bitnami/etcd:3.5
    container_name: etcd-v3
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        ipv4_address: 172.19.0.3

  mariadb:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Shanghai
    volumes:
      - ../../deploy/conf/mysql/sql:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        ipv4_address: 172.19.0.4

  redis:
    hostname: redis
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        ipv4_address: 172.19.0.5

  tdengine:
    image: tdengine/tdengine
    container_name: tdengine
    hostname: tdengine
    ports:
      - "6030:6030"
      - "6035:6035"
      - "6041:6041"
      - "6030-6040:6030-6040/udp"
    restart: always
    tty: true
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        ipv4_address: 172.19.0.6

  init-db:
    image: tdengine/tdengine
    container_name: init-db
    depends_on:
      - tdengine
    volumes:
      - ./init-db.sh:/init-db.sh
    command: /bin/bash /init-db.sh
    networks:
      ithings_net:
        ipv4_address: 172.19.0.9

  emqx:
    container_name: emqx
    image: emqx/emqx
    hostname: node1.emqx.io
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    volumes:
      - ../../deploy/conf/emqx/etc/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ../../deploy/conf/emqx/data/loaded_plugins:/opt/emqx/data/loaded_plugins
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=node1.emqx.io"
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    networks:
      ithings_net:
        ipv4_address: 172.19.0.7
